# Generated by Django 5.2.11 on 2026-03-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.BigIntegerField(help_text='รหัสหนังสือ (Numeric-only)', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='เช่น ชั้น A1', max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Maintenance'), ('Lost', 'Lost')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('ssid', models.BigIntegerField(help_text='รหัสสมาชิก (Numeric-only, เช่น 10000001)', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('tx_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RETURNED', 'RETURNED'), ('OVERDUE', 'OVERDUE')], default='ACTIVE', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='library_app.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='library_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='AdminAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_profile', to='library_app.member')),
            ],
        ),
    ]
