# Generated by Django 5.2.11 on 2026-03-01 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='AvailableCopies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='TotalCopies',
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='RenewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowingrecord',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Returned', 'Returned'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='fine',
            name='FineAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fine',
            name='Status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(max_length=50, unique=True)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed'), ('Lost', 'Lost'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
            ],
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='BookCopyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.bookcopy'),
        ),
    ]
